### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z

### ISSUE THREAD

**Issue by itsjustvenky** [dbmdz/iiif-presentation-api#12]
Why I am getting this error

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:571)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
        at de.digitalcollections.iiif.presentation.model.impl.jackson.v2.IiifPresentationApiObjectMapper.<init>(IiifPresentationApiObjectMapper.java:76)
```

I am using jackson lib (2.9.1). core, bindings, annotations, iiif-presentation-model-impl-3.3.0-SNAPSHOT.jar,  iiif-presentation-model-api-3.3.0-SNAPSHOT.jar

and I am running this app on Java 8.

Any clues ??

**Comment by jbaiter** [comment]
Can you do a `mvn dependency:tree` and check if you have by any chance multiple versions of Jackson on your classpath? My guess is that you have classes from Jackson <= 2.7 in there, since `requiresPropertyOrdering` was removed in 2.8. This might come from a transitive dependency.
